# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.cache/wt [current_project]
set_property parent.project_path D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl.xci
set_property used_in_implementation false [get_files -all d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl/user_design/constraints/M_DdrCtrl.xdc]
set_property used_in_implementation false [get_files -all d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl/user_design/constraints/M_DdrCtrl_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.runs/M_DdrCtrl_synth_1 -new_name M_DdrCtrl -ip [get_ips M_DdrCtrl]]

if { $cached_ip eq {} } {

synth_design -top M_DdrCtrl -part xc7k325tffg900-2 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix M_DdrCtrl_ M_DdrCtrl.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ M_DdrCtrl_stub.v
 lappend ipCachedFiles M_DdrCtrl_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ M_DdrCtrl_stub.vhdl
 lappend ipCachedFiles M_DdrCtrl_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ M_DdrCtrl_sim_netlist.v
 lappend ipCachedFiles M_DdrCtrl_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ M_DdrCtrl_sim_netlist.vhdl
 lappend ipCachedFiles M_DdrCtrl_sim_netlist.vhdl

 config_ip_cache -add -dcp M_DdrCtrl.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips M_DdrCtrl]
}

rename_ref -prefix_all M_DdrCtrl_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef M_DdrCtrl.dcp
create_report "M_DdrCtrl_synth_1_synth_report_utilization_0" "report_utilization -file M_DdrCtrl_utilization_synth.rpt -pb M_DdrCtrl_utilization_synth.pb"

if { [catch {
  file copy -force D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.runs/M_DdrCtrl_synth_1/M_DdrCtrl.dcp d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.runs/M_DdrCtrl_synth_1/M_DdrCtrl.dcp d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.runs/M_DdrCtrl_synth_1/M_DdrCtrl_stub.v d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.runs/M_DdrCtrl_synth_1/M_DdrCtrl_stub.vhdl d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.runs/M_DdrCtrl_synth_1/M_DdrCtrl_sim_netlist.v d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.runs/M_DdrCtrl_synth_1/M_DdrCtrl_sim_netlist.vhdl d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.ip_user_files/ip/M_DdrCtrl]} {
  catch { 
    file copy -force d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl_stub.v D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.ip_user_files/ip/M_DdrCtrl
  }
}

if {[file isdir D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.ip_user_files/ip/M_DdrCtrl]} {
  catch { 
    file copy -force d:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.srcs/sources_1/ip/M_DdrCtrl/M_DdrCtrl_stub.vhdl D:/Project_MySelf/1_LcdDis/Vivado/M_Ddr/M_Ddr.ip_user_files/ip/M_DdrCtrl
  }
}
