# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.cache/wt [current_project]
set_property parent.project_path D:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/src/M_Dvi.vhd
read_ip -quiet D:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll.xci
set_property used_in_implementation false [get_files -all d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll.xdc]
set_property used_in_implementation false [get_files -all d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll_ooc.xdc]

read_ip -quiet D:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_Dvi_ila/M_Dvi_ila.xci
set_property used_in_synthesis false [get_files -all d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_Dvi_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_Dvi_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_Dvi_ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_Dvi_ila/M_Dvi_ila_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/constrs_1/new/M_Dvi.xdc
set_property used_in_implementation false [get_files D:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/constrs_1/new/M_Dvi.xdc]


synth_design -top M_Dvi -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef M_Dvi.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file M_Dvi_utilization_synth.rpt -pb M_Dvi_utilization_synth.pb"
