# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll.xci
# IP: The module: 'M_ClkPll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'M_ClkPll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll.xdc
# XDC: The top module name and the constraint reference have the same name: 'M_ClkPll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'M_ClkPll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll.xci
# IP: The module: 'M_ClkPll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'M_ClkPll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll.xdc
# XDC: The top module name and the constraint reference have the same name: 'M_ClkPll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Project_MySelf/1_LcdDis/Vivado/M_Dvi/M_Dvi.srcs/sources_1/ip/M_ClkPll/M_ClkPll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'M_ClkPll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
